// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Packet ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Packet ) UnmarshalJSON([]byte) error { return nil }
func ( Packet ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Packet ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Packet *Packet

func ( Peer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Peer ) UnmarshalJSON([]byte) error { return nil }
func ( Peer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Peer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Peer *Peer
